# Generated by Django 2.0.7 on 2018-07-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180717_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
